# Generated by Django 5.0.4 on 2024-05-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TitlePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=9)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
