# Generated by Django 5.0.4 on 2024-05-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titlepage', '0003_titlepage_dep_titlepage_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titlepage',
            old_name='dep',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='titlepage',
            old_name='user',
            new_name='name',
        ),
    ]
